### ISSUE TITLE
involute-gear-collection dxf and stl files + python script

### ISSUE THREAD

**Issue by koppi** [jnweiger/inkscape-gears-dev#25]
I changed ```gear-dev.py``` as follows:

* removed the dependency on Inkscape,
* add dependency on ezdxf to generate dxf files.

It is intended to work with http://openscad.org/ and http://www.cammill.org/

Source code and shell scripts: https://github.com/koppi/involute-gear-collection

Have fun!

**Comment by Neon22** [comment]
Why not instead  factor it out into two diff files and import the common one.
Then inkscape plugin and your code can use same gears only oriented python file - which will make updating it much easier ?

**Comment by koppi** [comment]
I just created a nodejs version of Dr. Rainer Hessmer's [Online Involute Spur Gear Builder](http://www.hessmer.org/blog/2014/01/01/online-involute-spur-gear-builder/), see:

https://github.com/koppi/involute-gear-generator

I will remove my Python variant from my involute-gear-collection repo, but I leave the script [here](https://gist.github.com/koppi/2e45f344106474961909) for future reference.

**Comment by koppi** [comment]
I just came across another option to create DXF files of involute gears:

OpenScad with the MCAD library, see screenshot:

![20150521-003](https://cloud.githubusercontent.com/assets/9458631/7753562/834c9f5a-ffe6-11e4-88d8-cc23e5d57a4e.png)

**Comment by Neon22** [comment]
The only problem with the boolean style gear genberation is the artifacts from not enough samples.
Inkscape has a nice implementation of this as well - which can be used to make weird shaped gears like porpoises etc.
Greg frosts scad code is also boolean based.
The code we have tried to make uses a math based shape approach instead and does not suffer from artifacts of this type.
So two diff approaches. no problems - YMMV.

**Comment by koppi** [comment]
2015-05-22 7:54 GMT+02:00 Neon22 <notifications@github.com>:

> Inkscape has a nice implementation of this as well - which can be used to
> make weird shaped gears like porpoises etc.


​Do you think of ​unordinary_gears.inx here? – Or is there another approach
I'm not aware of?!

**Comment by Neon22** [comment]
yes that's it - Id forgotten its name momentarily.
